# -*- coding: utf-8 -*-
"""indexing,slicing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KO9qWjniE8h6C9caqH_3A9ILlBQkTxqu
"""

#indexing - accessing individual elements
#slicing - extracting subarrays using start:stop:step
#boolean indexing - filtering based on conditions
#filtering - selecting specific elements directly using conditions

#indexing
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[1])

arr=np.array([[1,2,3],[4,5,6]])
print(arr[1][2])

#slicing, start:stop:step
arr=np.array([1,2,3,4])
print(arr[1:3]) #inclusive:exclusive
print(arr[1:])
print(arr[-1]) #last ele
print(arr[::-1]) #rev
print(arr[1:4:2]) #step

import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr[1:3,2:4])

#boolean indexing
arr=np.array([1,2,3,4,5])
print(arr[arr>2])
print(arr[arr%2==0])

arr1=np.array([1,2,3,4,5])
print(arr1[(arr1 > 2) & (arr1 < 5)])

#reshaping - used to change shape of array
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)
reshaped=arr.reshape(2,3)
print(reshaped)

reshaped[0][0] = 100
print("reshaped arr=", reshaped)
print("original arr=", arr) #it impacts ori arr too

#ravel - flatters multi dimensional arr to 1d arr
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
ravel=arr.ravel()
ravel[0]=100
print(ravel)
print(arr)

#flatten - similar to ravel(), but returns copy (changes do not affect original arr)
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
flatten=arr.flatten()
print(flatten)
flatten[0]=900
print("after faltten=", flatten)
print("before faltten=", arr)

#hstack - joins arrays horizontally (axis 1) col wise
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
hstack=np.hstack((arr1,arr2))
print(hstack)

#vstack - joins arrays vertically (axis 0) row wise
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
vstack=np.vstack((arr1,arr2))
print(vstack)

#concatenate
print(np.concatenate([arr1,arr2]))

#transpose - .T
arr=np.array([[1,2],[3,4]])
print(arr.T)

#rand - generate a random float between 0 and 1
#randint - generate a random integer
import numpy as np
print(np.random.rand()) #print 0 to 1
print(np.random.rand(5)) #arr from 0 to 1
print(np.random.randint(10)) #random int
print(np.random.randint(0,10,size=5))

#random distribution
import numpy as np
print(np.random.normal(loc=50, scale=10,size=4)) #loction na avg, scale na standard deviation,size na input size

#uniform distribution
print(np.random.uniform(5,15,4))


#np.random.seed(42)

#Same output every time
#Needed for reproducibility
#📌 Interview keyword: Reproducibility

#linear algebra
import numpy as np
from numpy.linalg import inv,det

#matrix multiplication
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8],[9,10],[11,12]])
x=np.matmul(a,b)
print(x)

#matrix inverse
c=np.array([[1,2],[3,4]])
inv=inv(c)
print(inv)

#determinant
det=det(c)
print(det)